services:
  db:
    restart: always

  api:
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    restart: always

  frontend:
    context: .           # raiz do projeto
    dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - api
    restart: always