import type { ResourceConfig } from '@/types/resource'

export const auditLogsConfig: ResourceConfig = {
  key: 'audit-logs',
  label: 'Audit Log',
  pluralLabel: 'Audit Logs',
  endpoint: '/admin/audit-logs',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'action',
      label: 'Action',
      type: 'select',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
      selectOptions: [
        { label: 'Create', value: 'create' },
        { label: 'Edit', value: 'edit' },
        { label: 'Delete', value: 'delete' },
        { label: 'Cancel', value: 'cancel' },
      ],
    },
    {
      key: 'entity_type',
      label: 'Entity Type',
      type: 'text',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: true,
      readonly: true,
    },
    {
      key: 'entity_id',
      label: 'Entity ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'user_id',
      label: 'User ID',
      type: 'number',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'description',
      label: 'Description',
      type: 'textarea',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'created_at',
      label: 'Created',
      type: 'date',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
  ],
  relatedLists: [],
  extraActions: [],
}
