import type { ResourceConfig } from '@/types/resource'

export const clientsConfig: ResourceConfig = {
  key: 'clients',
  label: 'Client',
  pluralLabel: 'Clients',
  endpoint: '/admin/clients',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'name',
      label: 'Name',
      type: 'text',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: true,
      readonly: false,
    },
    {
      key: 'email',
      label: 'Email',
      type: 'email',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: false,
      readonly: false,
    },
    {
      key: 'document',
      label: 'Document',
      type: 'text',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: false,
      filterable: false,
      readonly: false,
    },
    {
      key: 'plan_id',
      label: 'Plan',
      type: 'relation',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: false,
      filterable: false,
      readonly: false,
      relation: {
        resource: 'plans',
        labelField: 'name',
        valueField: 'id',
      },
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: false,
      readonly: false,
      selectOptions: [
        { label: 'Active', value: 'active' },
        { label: 'Overdue', value: 'overdue' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
    },
    {
      key: 'efi_subscription_id',
      label: 'Efi Subscription ID',
      type: 'text',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'checkout_url',
      label: 'Checkout URL',
      type: 'text',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'cancelled_at',
      label: 'Cancelled At',
      type: 'date',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'created_at',
      label: 'Created',
      type: 'date',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'updated_at',
      label: 'Updated',
      type: 'date',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
  ],
  relatedLists: [
    {
      label: 'Payments',
      resource: 'payments',
      foreignKey: 'client_id',
      fields: [
        {
          key: 'id',
          label: 'ID',
          type: 'number',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'amount',
          label: 'Amount',
          type: 'number',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'status',
          label: 'Status',
          type: 'text',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'paid_at',
          label: 'Paid At',
          type: 'date',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'created_at',
          label: 'Created',
          type: 'date',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
      ],
    },
  ],
  extraActions: [],
}
