import type { ResourceConfig } from '@/types/resource'

export const paymentsConfig: ResourceConfig = {
  key: 'payments',
  label: 'Payment',
  pluralLabel: 'Payments',
  endpoint: '/admin/payments',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'client_id',
      label: 'Client ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'plan_id',
      label: 'Plan ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'amount',
      label: 'Amount',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
      selectOptions: [
        { label: 'Confirmed', value: 'confirmed' },
        { label: 'Failed', value: 'failed' },
      ],
    },
    {
      key: 'transaction_id',
      label: 'Transaction ID',
      type: 'text',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
    {
      key: 'paid_at',
      label: 'Paid At',
      type: 'date',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'created_at',
      label: 'Created',
      type: 'date',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
  ],
  relatedLists: [],
  extraActions: [],
}
