import type { ResourceConfig } from '@/types/resource'

export const plansConfig: ResourceConfig = {
  key: 'plans',
  label: 'Plan',
  pluralLabel: 'Plans',
  endpoint: '/admin/plans',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'name',
      label: 'Name',
      type: 'text',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: true,
      readonly: false,
    },
    {
      key: 'description',
      label: 'Description',
      type: 'textarea',
      showInList: false,
      showInForm: true,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: false,
    },
    {
      key: 'price',
      label: 'Price',
      type: 'number',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: false,
      readonly: false,
    },
    {
      key: 'billing_cycle',
      label: 'Billing Cycle',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: false,
      readonly: false,
      selectOptions: [
        { label: 'Weekly', value: 'weekly' },
        { label: 'Monthly', value: 'monthly' },
        { label: 'Yearly', value: 'yearly' },
      ],
    },
    {
      key: 'efi_plan_id',
      label: 'Efi Plan ID',
      type: 'text',
      showInList: false,
      showInForm: true,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: false,
    },
    {
      key: 'split_config_id',
      label: 'Split Config',
      type: 'relation',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: false,
      relation: {
        resource: 'split-configs',
        labelField: 'name',
        valueField: 'id',
      },
    },
    {
      key: 'is_active',
      label: 'Active',
      type: 'boolean',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: false,
    },
    {
      key: 'created_at',
      label: 'Created',
      type: 'date',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'updated_at',
      label: 'Updated',
      type: 'date',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
  ],
  relatedLists: [
    {
      label: 'Clients',
      resource: 'clients',
      foreignKey: 'plan_id',
      fields: [
        {
          key: 'id',
          label: 'ID',
          type: 'number',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'name',
          label: 'Name',
          type: 'text',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'email',
          label: 'Email',
          type: 'email',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'status',
          label: 'Status',
          type: 'text',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
        {
          key: 'created_at',
          label: 'Created',
          type: 'date',
          showInList: true,
          showInForm: false,
          showInDetail: false,
          required: false,
          sortable: false,
          filterable: false,
          readonly: true,
        },
      ],
    },
  ],
  extraActions: [],
}
