import type { ResourceConfig } from '@/types/resource'

export const splitConfigsConfig: ResourceConfig = {
  key: 'split-configs',
  label: 'Split Config',
  pluralLabel: 'Split Configs',
  endpoint: '/admin/split-configs',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'name',
      label: 'Name',
      type: 'text',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: true,
      readonly: false,
    },
    {
      key: 'created_at',
      label: 'Created',
      type: 'date',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'updated_at',
      label: 'Updated',
      type: 'date',
      showInList: false,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: false,
      filterable: false,
      readonly: true,
    },
  ],
  relatedLists: [],
  extraActions: [],
}
