import type { ResourceConfig } from '@/types/resource'

export const usersConfig: ResourceConfig = {
  key: 'users',
  label: 'User',
  pluralLabel: 'Users',
  endpoint: '/admin/users',
  fields: [
    {
      key: 'id',
      label: 'ID',
      type: 'number',
      showInList: true,
      showInForm: false,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: true,
    },
    {
      key: 'email',
      label: 'Email',
      type: 'email',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: true,
      readonly: false,
    },
    {
      key: 'role',
      label: 'Role',
      type: 'select',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: true,
      sortable: true,
      filterable: false,
      readonly: false,
      selectOptions: [
        { label: 'Admin', value: 'admin' },
        { label: 'Viewer', value: 'viewer' },
      ],
    },
    {
      key: 'is_active',
      label: 'Active',
      type: 'boolean',
      showInList: true,
      showInForm: true,
      showInDetail: true,
      required: false,
      sortable: true,
      filterable: false,
      readonly: false,
    },
  ],
  relatedLists: [],
  extraActions: [],
}
